CREATE DATABASE IF NOT EXISTS petclinic CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'dev33'@'%' IDENTIFIED BY 'ezflow_010';
GRANT ALL PRIVILEGES ON petclinic.* TO 'dev33'@'%';
FLUSH PRIVILEGES;
